services:
  postgres:
    container_name: postgres_container_pst_2
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mage:
    container_name: mage_container_pst_2
    image: mageai/mageai:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6789:6789"
    environment:
      MAGE_DATABASE_CONNECTION_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}        
    volumes:
      - ./mage_ai_volume:/home/src

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container_pst_2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_volume:/var/lib/pgadmin

    depends_on:
      - postgres


      